### ISSUE TITLE
Práctica_4

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo_tec#1]
[Practica4.pdf](https://github.com/user-attachments/files/17121414/Practica4.pdf)

**Comment by JORGELUIS2266** [comment]
DE ACUERDO A LA RUBRICA TIENE UN PORCENTAJE DE 20% DE 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
